### ISSUE TITLE
Some new methods showing as invalid functions

### ISSUE THREAD

**Issue by TheHolyWaterme1on** [jo3-l/action-check-yag-tmpl-syntax#9]
Dearest Joseph,

It appears that the _break_ and _return_ functions are not recognised as valid by the syntax checker, and it returns a failed check whenever either of these are present. The same error did not occur for _continue_.
Please take this into consideration.

Sincerely,
 T. H. Watermelon

**Comment by jo3-l** [comment]
Please link to the relevant Actions run.
